Story_6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story6/', include('status.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('story10/', include('story10.urls'))
]

home/urls.py
from django.urls import path
from . import views

app_name = 'beranda'

urlpatterns = [
    path('', views.home, name='index'),
]

status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.index, name='index'),
]

story10/urls.py
from django.urls import path, include
from .views import index10

app_name = 'story10'

urlpatterns = [
    path('', index10, name='index10')
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='index'),
]

story8/urls.py
from django.urls import path
from .views import index8, ambil_buku

app_name = 'story8'

urlpatterns = [
    path('', index8, name='index8'),
    path('get/<judul>', ambil_buku)
]

story9/urls.py
from django.urls import path, include
from .views import index9, register

app_name = 'story9'

urlpatterns = [
    path('', index9, name='index9'),
    path('auth/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
]

home/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=300)
    time = models.DateTimeField(default=timezone.now)

story10/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

status/forms.py
from django import forms
from django.forms import ModelForm
from .models import Status

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['status']
        widgets = { 
            'status': forms.TextInput(attrs={
                'placeholder':'Ketik disini :)'
            }),
        }

story9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, help_text='Required. Please fill in your first name.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, required=False, help_text='Optional. You can reset your password if a correct email is informed.')
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

status/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StatusForm
from .models import Status
# Create your views here.

def index(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/story6/')

    else:
        form = StatusForm()
        list_status = Status.objects.all().order_by('-time')
        context = {'form':form, 'list_status':list_status}
        return render(request, 'index.html', context)

story10/views.py
from django.shortcuts import render

# Create your views here.

def index10(request):
    return render(request, 'index10.html')

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story7index.html', context={})

story8/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import requests

# Create your views here.
def index8(request):
    r = requests.get('https://www.googleapis.com/books/v1/volumes?q=dog%20days')
    context = {'result':r.json()}
    return render(request, 'story8index.html', context)

def ambil_buku(request, judul):
    r = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + judul)
    return JsonResponse(r.json())

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import RegForm
from django.contrib.auth import login, authenticate

# Create your views here.
def index9(request):
    if request.user.is_authenticated:
        context = {'user': request.user}
        return render(request, 'story9index.html', context)
    else:
        return render(request, 'story9landingpage.html')

def register(request):
    if request.user.is_authenticated:
        return redirect('story9:index9')
    else:
        if request.method == "POST":
            form = RegForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect('story9:index9')
        else:
            form = RegForm()
        return render(request, 'registration/regPage.html', {'form': form})

home/templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=McLaren|Quicksand&display=swap" rel="stylesheet">    
    <title>Ronaldi Tjaidianto - Profil Web</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    <div class="kontainer" id="beranda">
        <div class="tron">
                <img src="static/asset/asset1.jpg">
                <h1>Ronaldi <br> Tjaidianto</h1>
                <hr>
                <h3>Mahasiswa.<br>
                    Quanta.<br>
                    CSUI 2018.
                </h3>
                <a href="#profil"><img id="down" src="static/asset/asset2.png"></a>
        </div>
    </div>
    
    <div class="kontainer" id="profil">
        <h2>Profil</h2>
        <div class="konten mx-auto">
            <img src="static/asset/Ronaldi.jpg">
            <div class="tabel">
                <table>
                    <tr>
                        <td>Nama</td>
                        <td class="data">: Ronaldi Tjaidianto</td>
                    </tr>
                    <tr>
                        <td>Pekerjaan</td>
                        <td class="data">: Mahasiswa</td>
                    </tr>
                    <tr>
                        <td>Universitas</td>
                        <td class="data">: Universitas Indonesia</td>
                    </tr>
                    <tr>
                        <td>Jurusan</td>
                        <td class="data">: Ilmu Komputer</td>
                    </tr>
                    <tr>
                        <td>Angkatan</td>
                        <td class="data">: 2018</td>
                    </tr>
                    <tr>
                        <td>NPM</td>
                        <td class="data">: 1806141441</td>
                    </tr>
                </table>
            </div>
            <h4>Tentang Saya</h4>
            <p>Saya mahasiswa jenjang sarjana di Fasilkom UI. Saya telah mempelajari pemrograman<br>
                web dan laman ini merupakan salah satu hasil dari pembelajaran tersebut.</p>
        </div>
    </div>
    <div class="kontainer" id="pengalaman">
        <h2>Pengalaman</h2>
        <div class="konten mx-auto">
            <div class="sub-konten">
                    <h4>Pendidikan</h4>
                    <ul>
                        <li><p>
                            Fakultas Ilmu Komputer, Universitas Indonesia <br>
                            2018 - Sekarang <br>
                            -- <i>Tools:</i> Python, Java
                        </p></li>
                        <li><p>
                            SMAN 7 Banjarmasin <br>
                            2015 - 2018 <br>
                            -- Peminatan: Matematika dan IPA
                        </p></li>
                    </ul>
                </div>
                <div class="sub-konten">
                    <h4>Organisasi</h4>
                    <ul>
                        <li><p>
                            Wakil Koordinator Humas OSUI Mahawaditra <br>
                            2019 - sekarang <br>
                            -- Mengatur publikasi eksternal dan website OSUI Mahawaditra
                        </p></li>
                        <li><p>
                            Staf Desain Humas OSUI Mahawaditra <br>
                            2018 - 2019 <br>
                            -- <i>Tools:</i> Adobe Photoshop, Adobe Illustrator
                        </p></li>
                        <li><p>
                            Staf Desain Paramita KMBUI<br>
                            2018 - 2019 <br>
                            -- <i>Tools:</i> Adobe Indesign, Adobe Photoshop
                        </p></li>
                    </ul>
                </div>
        </div>
    </div>
    <div class="kontainer" id="kontak">
        <h2>Kontak</h2>
        <div class="sub-kontainer mx-auto">
            <a href="https://www.instagram.com/ronaldi.tj">
                <img class="icon" src="static/asset/ig.png"><p>ronaldi.tj</p></a>
            <img class="icon" src="static/asset/line.png">
            <p>ronaldi1</p>
            <img class="icon" src="static/asset/asset3.png">
            <p>ronaldi.tjaidianto@ui.ac.id</p>
        </div>
    </div>
    <footer>
        <div>
            <a href="#beranda"><img src="static/asset/asset2.png"><p>Kembali ke atas</p></a>
        </div>
    </footer>
</body>
</html>

home/templates/navbar.html
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<nav class="navbar fixed-top navbar-expand-sm navbar-dark" style="background-color: #011C37;">
    <a class="navbar-brand" href="{% url 'beranda:index'%}" style="font-family: 'Grand Hotel'; font-weight: 400; font-size: 16px; font-style: italic; line-height: 15px;">Ronaldi<br>Tjaidianto</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarDropdown" aria-controls="navbarDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarDropdown" style="font-family: 'Quicksand';">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'beranda:index'%}#beranda">Beranda</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'beranda:index'%}#profil">Profil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'beranda:index'%}#pengalaman">Pengalaman</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'beranda:index'%}#kontak">Kontak</a>
            </li>
            <li class="nav-item dropdown pl-1" style="display: flex;align-items: center;">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown5" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size: 93%;">
                  Story
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdown5" style="right: 0 !important; left: auto !important;">
                  <a class="dropdown-item" href="{% url 'status:index'%}">Status Log</a>
                  <a class="dropdown-item" href="{% url 'story7:index'%}">Profil Singkat</a>
                  <a class="dropdown-item" href="{% url 'story8:index8'%}">Perpustakaan Daring</a>
                  <a class="dropdown-item" href="{% url 'story9:index9'%}">Autentikasi</a>
                </div>
            </li>

        </ul>
    </div>
</nav>

status/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=McLaren|Quicksand&display=swap" rel="stylesheet">    
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Story 6</title>
</head>
<body style="font-family: 'Quicksand'; background: #d9effc;  color: #0b5058;">
    {% include 'navbar.html' %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 text-center mt-5" style="font-family: 'McLaren';">
            <h1 style="font-size: 300%; padding-top: 30px;">Halo, apa kabar?</h1>
        </div>
    </div>

    <div class="row" style="font-size: 18px;">
        <div class="col-lg-12 col-md-12 col-sm-12 align-items-center text-center mx-auto mt-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Masukkan!">
            </form>
        </div>
    </div>

    <div class="row align-items-center mx-auto text-center mt-4">
        <div class="col-6">
            <b>Status</b>
        </div>
        <div class="col-6">
            <b>Waktu</b>
        </div>
    </div>

    {% for el in list_status %}
    <div class="row align-items-center mx-auto text-center mt-1">
        <tr>
            <div class="col-6" style="overflow: auto;">
                <th>{{el.status}}</th>
            </div>
            <div class="col-6">
                <th>{{el.time}}</th>
            </div>
        </tr>
    </div>
    {% endfor %}
</body>
</html>

story10/templates/index10.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=McLaren|Quicksand&display=swap" rel="stylesheet">    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Story 10</title>
</head>
<body style="font-family: 'Quicksand'; padding: 50px;">
    <h1 class="text-center" style="font-weight: bolder;">Load Balancer</h1> <br>
    <p>
        Load balancer adalah suatu alat yang digunakan untuk mendistribusikan <i>network traffic</i> atau
        <i>request</i> yang muncul secara efisien ke sebuah kumpulan server atau yang biasa disebut sebagai <i>server farm / server pool</i>.
        Load balancer akan meneruskan <i>request</i> yang dikirimkan pengguna kepada server yang tersedia menggunakan algoritma tertentu sehingga
        tidak ada server yang 'bekerja berlebihan'. Dengan menggunakan load balancer, <i>high availability</i> suatu layanan web akan terjamin, sehingga
        pengguna akan selalu dapat mengakses layanan web tersebut.
    </p>
    <p>
        Salah satu load balancer yang dapat digunakan adalah Nginx. Disini akan dibahas tentang implementasi load balancer menggunakan Nginx
        untuk menangani layanan web sederhana.
        <ol>
            <li>
                <b>Unduh Nginx</b> <br>
                Nginx dapat diunduh melalui <a href="http://nginx.org/en/download.html">http://nginx.org/en/download.html</a>.
            </li>
            <li>
                <b>Konfigurasi Nginx</b> <br>
                Setelah selesai mengunduh Nginx, ekstrak file tersebut kemudian buka file <i>nginx.conf</i> pada folder conf. <br>
                Kemudian, ubah konten pada tag http menjadi sebagai berikut: <br>
                <img src="{% static 'img1.PNG' %}" alt="code http" style="width: 25%; padding: 10px;"> <br>
                Yang dilakukan oleh kode diatas adalah 
                <ul>
                    <li>
                        upstream <br>
                        => Mendefinisikan server yang akan digunakan yaitu localhost:8000 dan localhost:9000.
                    </li>
                    <li>
                        server <br>
                        => Server ini akan menerima <i>request</i> dan akan meneruskannya kepada upstream.
                    </li>
                </ul>
            </li>
            <li>
                <b>Jalankan Nginx</b> <br>
                Untuk menjalankan Nginx, dapat dilakukan dengan <i>double click</i> pada <u>nginx.exe</u> atau 
                dengan menjalankan <i>start nginx</i> pada command line di folder Nginx berada.
            </li>
        </ol> 
    </p>
    <p>
        Untuk menguji konfigurasi diatas, dibawah ini ditampilkan sebuah aplikasi sederhana yang akan menampilkan port yang sedang digunakan. <br>
        Karena server yang digunakan adalah localhost pada port 8000 dan 9000, server pada port tersebut harus dinyalakan terlebih dahulu.
        Kemudian, ketika kita mengakses localhost pada browser yang muncul adalah sebagai berikut: <br>
        <div>
            <img src="{% static 'img2.png' %}" alt="ss1" style="width: 70%;"> 
        </div>
        <br>
        Ketika kita me-<i>refresh</i> halaman tersebut yang muncul adalah sebagai berikut:
        <br><br>
        <div>
            <img src="{% static 'img3.png' %}" alt="ss2" style="width: 70%;">
        </div>
        <br>
        Dari kedua gambar tersebut, dapat dilihat bahwa server yang melayani request berganti-ganti. Hal ini menunjukkan bahwa load balancer sudah berjalan.
    </p>
</body>
</html>

story7/templates/story7index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">    
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">
    <!-- CSS & Bootstrap -->
    <link href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href= "{% static 'css/story7.css' %}">
    <!-- javaScript & jQuery -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'javascript/story7.js' %}"></script>
    <title>Story 7</title>
</head>
<body class="light" id="body">
    {% include 'navbar.html' %}
    <div class="custom-control custom-switch text-center mt-3" style="padding-top: 60px;">
        <input type="checkbox" class="custom-control-input" id="customSwitch1" onclick="changeClass()">
        <label class="custom-control-label" for="customSwitch1" id="tombol">Ubah tema!</label>
    </div>

    <div class="text-center mt-4">
        <h1><b id="hai">Hai!</b> Hi!</h1>
        <h2>你好! 안녕! こんにちは!</h2>
    </div>

    <div id="accordion" class="col-6 mx-auto mt-5 text">
        <h3>Aktivitas</h3>
        <div>
            <p style="text-align: justify;">
            Saat ini saya sedang menjalani perkuliahan tingkat sarjana di Fakultas Ilmu Komputer, Universitas Indonesia.
            Selain itu, saya juga tergabung sebagai anggota pada Orkestra Simfoni Universitas Indonesia Mahawaditra dan
            Keluarga Mahasiswa Buddhis Universitas Indonesia.
            </p>
        </div>
        <h3>Pengalaman Organisasi/Kepanitiaan</h3>
        <div>
            <h6>Organisasi</h6>
            <ul>
                <li>Wakil Koordinator Humas OSUI Mahawaditra (2019-sekarang)</li>
                <li>Staf Humas OSUI Mahawaditra (2018-2019)</li>
                <li>Staf Paramita KMBUI (2018-2019)</li>
            </ul>
            <h6>Kepanitiaan</h6>
            <ul>
                <li>Staf Desain Misi Edukasi OSUI Mahawaditra (2019)</li>
                <li>Staf Desain Konser MusiKampus OSUI Mahawaditra (2019)</li>
            </ul>
        </div>
    </div>
</body>
</html>

story8/templates/story8index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story 8</title>
    <link href="https://fonts.googleapis.com/css?family=McLaren&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
</head>
<body style="background: #d9effc;  color: #0b5058;">
    {% include 'navbar.html' %}
    <div class="row mt-5 text-center">
        <div class="col" style="font-family: 'McLaren';">
            <h1 style="font-size: 300%; padding-top: 30px;">Hai! Mau cari buku apa?</h1>
        </div>
    </div>
    <div class="row mt-1">
        <div class="col text-center">
            <input type="text" name="" id="field" placeholder="Cari disini">
            <button type="submit" id="tombol">Cari!</button>
        </div>
    </div>
    
    <table class="align-items-center mx-auto mt-3 table table-bordered" id="hasil">
        <tr>
            <th>Cover</th>
            <th>Judul</th>
            <th>Penulis</th>
            <th>Deskripsi</th>
        </tr>
        {% for el in result.items %}
            <tr>
                <td><img src="{{el.volumeInfo.imageLinks.thumbnail}}" alt=""></td>
                <td>{{el.volumeInfo.title}}</td>
                <td>
                    <ul>
                    {% if el.volumeInfo.authors not in el %}
                        <li>Unknown</li>
                    {%else%}
                        {% for author in el.volumeInfo.authors %}
                        <li>{{author}}</li>
                        {% endfor %}
                    {%endif%}
                    </ul>
                </td>
                <td>{{el.volumeInfo.description}}</td>
            </tr>
        {% endfor %}
    </table>
</body>
<script>
$(document).ready(() => {
    $("#tombol").click( function() {
        var apaja = $("#field").val();
        $.ajax({
            method: 'GET',
            url: "https://ronalditj.herokuapp.com/story8/get/" + apaja, 
            success: function(result){
                var judul = "<tr><th>Cover</th><th>Judul</th><th>Penulis</th><th>Deskripsi</th></tr>" 
                $("tbody").empty();
                $("tbody").append(judul);
                for(var j=0; j < 10 ; j++) {
                    var string = "<tr class=" + '"result"' + ">";
                    var buku = result.items[j];
                    // gambar
                    if (buku.volumeInfo.imageLinks == undefined)
                        string += "<td> Tidak Tersedia </td>";
                    else {
                        string += "<td><img src=" + buku.volumeInfo.imageLinks.thumbnail + "></td>";
                    }
                    // judul
                    string += "<td>" + buku.volumeInfo.title + "</td>";
                    // penulis
                    if (buku.volumeInfo.authors == undefined)
                        string += "<td> Unknown </td>";
                    else {
                        string += "<td><ul>";
                        for(var i =0; i < buku.volumeInfo.authors.length; i++){
                            string += "<li>"+buku.volumeInfo.authors[i] + "</li>";
                        }
                        string += "</ul></td>";
                    }
                    // description
                    if (buku.volumeInfo.description == undefined)
                        string += "<td> Tidak Tersedia </td>";
                    else {
                        string += "<td>" + buku.volumeInfo.description + "</td>";
                    }
                    string += "</tr>"
                    $("tbody").append(string);
                }
            }
        })
    })
})
</script>	
</html>

story9/templates/story9index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=McLaren&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
    <title>Story 9</title>
</head>
<body class="d-flex justify-content-center text-center h-100 align-items-center" style="background: #d9effc;  color: #0b5058; font-family: 'McLaren';">
    {% include 'navbar.html' %}
    <div>
        <h1 style="font-size: 400%;">Hello, {{user.get_full_name}}!</h1>
        <h2>Have a nice day! :)</h2>
        <button id="out">Logout</button>
    </div>
</body>
<script>
    $("#out").click( function() {
        location.href = "{% url 'story9:logout' %}";
    })
</script>
</html>

story9/templates/story9landingpage.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=McLaren|Quicksand&display=swap" rel="stylesheet">    
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
    <title>Story 9</title>
</head>
<body class="d-flex align-middle align-items-center justify-content-center text-center h-100" style="background: #d9effc;  color: #0b5058; font-family: 'McLaren';">
    {% include 'navbar.html' %}
    <div>
        <h1 style="font-size: 400%;">Log in or Register</h1>
        <h2 class="mb-3">to access this webpage :)</h2>
        <button id="login" type="button" class="btn btn-outline-dark mr-2">Log In</button>
        <button id="reg" type="button" class="btn btn-outline-dark">Register</button>
    </div>
</body>
<script>
    $("#login").click(function() {
        location.href = "{% url 'story9:login' %}";
    })
    $("#reg").click(function() {
        location.href = "{% url 'story9:register' %}";
    })
</script>
</html>